<?php

/** REDIS */
const REDIS_SERVER = '127.0.0.1';
const REDIS_PORT = '6379';
const REDIS_CONNECTION_TIMEOUT = '3';
const REDIS_LOCK_WAITING_TIME_US =  '1000';
const REDIS_RELEASE_LOCK_PROBABILITY =  '10';
const REDIS_LOCK_TTL = 5;